- hosts: all
  sudo: yes

  vars:
    elasticsearch_version: 5.3.1
    kibana_version: 5.3.1
    packetbeat_version: 5.3.1
    topbeat_version: 1.3.1
    filebeat_version: 5.3.1
    beats_dashboards_version: 1.1.0

  tasks:
    - name: "pexpectのインストール"
      shell: cd /tmp && wget https://bootstrap.pypa.io/get-pip.py && python get-pip.py && pip install pexpect
      
    - name: "PPAを追加する"
      shell: add-apt-repository ppa:openjdk-r/ppa && apt-get update
    - name: "OpenJDKとunzipをインストール"
      apt: name={{ item }} install_recommends=False update_cache=yes cache_valid_time=300
      with_items:
        - openjdk-8-jre-headless
        - unzip
    - name: "使用するJava VMを切り替える"
      expect:
        command: update-alternatives --config java
        responses:
          "Press enter to keep the current choice\\[\\*\\], or type selection number:" : "2"

    - name: "ダウンロードするファイルのリストを転送"
      template: src=templates/get_urls.txt dest=/tmp/ mode=755

    - name: "Elasticsearch, Kibana, Beatsとテストデータをダウンロード"
      shell: cd /tmp && cat /tmp/get_urls.txt | xargs -n 1 -P 4 wget -q

    - name: "Elasticsearchをdebパッケージからインストール"
      apt: deb=/tmp/elasticsearch-{{ elasticsearch_version }}.deb
    - name: "Packetbeatをdebパッケージからインストール"
      apt: deb=/tmp/packetbeat-{{ packetbeat_version }}-amd64.deb
    - name: "Topbeatをdebパッケージからインストール"
      apt: deb=/tmp/topbeat_{{ topbeat_version }}_amd64.deb
    - name: "Filebeatをdebパッケージからインストール"
      apt: deb=/tmp/filebeat-{{ filebeat_version }}-amd64.deb

    - name: "Elasticsearchを起動してサービスを有効化"
      service: name=elasticsearch state=started enabled=yes
    - name: "Elasticsearchの起動を待つ"
      wait_for: port=9200

    - name: "Kibanaをdebパッケージからインストール"
      apt: deb=/tmp/kibana-{{ kibana_version }}-amd64.deb
#   - name: "Kibana5のアーカイブを展開"
#     unarchive: copy=no src=/tmp/kibana-{{ kibana_version }}-linux-x64.tar.gz dest=/opt
#   - name: "Kibana5の起動スクリプトを転送"
#     template: src=templates/kibana.initscript dest=/etc/init.d/kibana mode=755
    - name: "Senseをインストール"
      shell: cd /usr/share/kibana/ && ./bin/kibana plugin --install elastic/sense
    - name: "Timelionをインストール"
      shell: cd /usr/share/kibana/ && ./bin/kibana plugin --install kibana/timelion
    - name: "Kibana5を起動してサービスを有効化"
      service: name=kibana state=started enabled=yes

    - name: "テストデータshakespeareのマッピングを転送"
      copy: src=shakespeare_schema.json dest=/tmp
    - name: "テストデータshakespeareのマッピングを作成"
      shell: curl -XPUT http://localhost:9200/shakespeare --data-binary @/tmp/shakespeare_schema.json
    - name: "テストデータshakespeareの投入"
      shell: curl -XPOST 'localhost:9200/shakespeare/_bulk?pretty' --data-binary @/tmp/shakespeare.json
    - name: "テストデータaccountsの投入"
      shell: cd /tmp && unzip accounts.zip\?raw\=true && curl -XPOST 'localhost:9200/bank/accounts/_bulk?pretty' --data-binary @/tmp/accounts.json
    - name: "テストデータlogstashの投入"
      shell: cd /tmp && gunzip logs.jsonl.gz && curl -XPOST 'localhost:9200/_bulk?pretty' --data-binary @/tmp/logs.jsonl

    - name: "Beatsのテンプレートを登録するスクリプトを転送"
      copy: src=beats-templates.sh dest=/tmp mode=755
    - name: "Beatsのダッシュボードを登録するスクリプトを転送"
      template: src=templates/beats-dashboard.sh dest=/tmp mode=755
    - name: Beatsのテンプレートを登録
      shell: cd /tmp && ./beats-templates.sh
    - name: Beatsのダッシュボードを登録
      shell: cd /tmp && ./beats-dashboard.sh

    - name: "Packetbeatを起動してサービスを有効化"
      service: name=packetbeat state=started enabled=yes
    - name: "Topbeatを起動してサービスを有効化"
      service: name=topbeat state=started enabled=yes
    - name: "Filebeatを起動してサービスを有効化"
      service: name=filebeat state=started enabled=yes
